pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Besso2003/Terraform_ITI.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Labs') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds']
                    ]) {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Labs') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds'],
                        file(credentialsId: 'prod-tfvars', variable: 'TFVARS')
                    ]) {
                        sh 'terraform plan -var-file=$TFVARS'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                input message: "Approve Apply?"
                dir('Labs') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds'],
                        file(credentialsId: 'prod-tfvars', variable: 'TFVARS')
                    ]) {
                        sh 'terraform apply -auto-approve -var-file=$TFVARS'
                    }
                }
            }
        }
    }
}