pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Besso2003/Terraform_ITI.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Labs') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds']
                    ]) {
                        sh '''
                            terraform init
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Labs') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds',
                         file(credentialsId: 'prod-tfvars', variable: 'TFVARS')]
                    ]) {
                        sh '''
                            cp $TFVARS prod.tfvars
                            terraform plan -var-file=prod.tfvars
                        '''
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Labs') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds'],
                        [$class: 'FileBinding',
                         credentialsId: 'prod-tfvars',
                         variable: 'TFVARS']
                    ]) {
                        sh '''
                            cp $TFVARS prod.tfvars
                            terraform apply -auto-approve -var-file=prod.tfvars
                        '''
                    }
                }
            }
        }
    }
}