- name: Configure app EC2 as Jenkins agent
  hosts: app
  become: yes

  vars:
    jenkins_home: /home/ec2-user/jenkins

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Install git
      yum:
        name: git
        state: present

    - name: Install Node.js 18
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        yum install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Create Jenkins agent working directory
      file:
        path: "{{ jenkins_home }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0755"

    - name: Ensure .ssh directory exists
      file:
        path: /home/ec2-user/.ssh
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0700"

    - name: Add Jenkins public key to authorized_keys
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', '/var/jenkins_home/.ssh/bastion-key.pub') }}"
    
    - name: Install pm2 globally
      shell: npm install -g pm2 --prefix /home/ec2-user/.npm-global
      become: yes
      become_user: ec2-user

    - name: Add npm-global to PATH in bashrc
      lineinfile:
      path: /home/ec2-user/.bashrc
      line: 'export PATH=$PATH:/home/ec2-user/.npm-global/bin'
      state: present